// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPePqAmN1F2FH5wBu1e13zciZL0JMFgK8',
    appId: '1:297299748261:web:55a8a1a0a8397bab87f44c',
    messagingSenderId: '297299748261',
    projectId: 'fir-b17d8',
    authDomain: 'fir-b17d8.firebaseapp.com',
    storageBucket: 'fir-b17d8.appspot.com',
    measurementId: 'G-W1ES80PF3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyd3XQhiZBtOYEu7NYP8bNWE7PazLKL9Y',
    appId: '1:297299748261:android:67bbf62340dae7ea87f44c',
    messagingSenderId: '297299748261',
    projectId: 'fir-b17d8',
    storageBucket: 'fir-b17d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDWAjmmrVnp1B0rDqciVaa1wgkFrhGqFI',
    appId: '1:297299748261:ios:9af9c24e80bd71aa87f44c',
    messagingSenderId: '297299748261',
    projectId: 'fir-b17d8',
    storageBucket: 'fir-b17d8.appspot.com',
    androidClientId: '297299748261-9bkairlso6cc350j4q9nf4301ebsbv6u.apps.googleusercontent.com',
    iosClientId: '297299748261-rrgrp105o2bbm0avq4sp38p19i8e3obc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktikClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDWAjmmrVnp1B0rDqciVaa1wgkFrhGqFI',
    appId: '1:297299748261:ios:9af9c24e80bd71aa87f44c',
    messagingSenderId: '297299748261',
    projectId: 'fir-b17d8',
    storageBucket: 'fir-b17d8.appspot.com',
    androidClientId: '297299748261-9bkairlso6cc350j4q9nf4301ebsbv6u.apps.googleusercontent.com',
    iosClientId: '297299748261-rrgrp105o2bbm0avq4sp38p19i8e3obc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktikClone',
  );
}
